version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ddi_governance
      POSTGRES_USER: ddi_user
      POSTGRES_PASSWORD: ddi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./governance-tools/sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  datahub-gms:
    image: acryldata/datahub-gms:latest
    ports:
      - "8080:8080"
    environment:
      EBEAN_DATASOURCE_DRIVER: org.postgresql.Driver
      EBEAN_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ddi_governance
      EBEAN_DATASOURCE_USERNAME: ddi_user
      EBEAN_DATASOURCE_PASSWORD: ddi_password
    depends_on:
      - postgres

  datahub-frontend:
    image: acryldata/datahub-frontend-react:latest
    ports:
      - "9002:9002"
    environment:
      DATAHUB_GMS_HOST: datahub-gms
      DATAHUB_GMS_PORT: 8080
    depends_on:
      - datahub-gms

  jaeger:
    image: jaegertracing/all-in-one:1.53
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      COLLECTOR_OTLP_ENABLED: true

volumes:
  postgres_data:
  redis_data: